const MODAL_BODY_TYPES = {
		USER_DETAIL: "USER_DETAIL",
		ADD_MANAGE_DELIVERYMAN: "ADD_MANAGE_DELIVERYMAN",
		ADD_MANAGE_DESK: "ADD_MANAGE_DESK",
		DELIVER_TO_CUSTOMER: "DELIVER_TO_CUSTOMER",
		ADD_MANAGE_ADMIN: "ADD_MANAGE_ADMIN",
		EDIT_SHIPMENT_WEIGHT: "EDIT_SHIPMENT_WEIGHT",
		ASSIGN_DELIVERY: "ASSIGN_DELIVERY",
		RETURN_TO_CUSTOMER: "RETURN_TO_CUSTOMER",
		ASSIGN_RETURN_DELIVERY: "ASSIGN_RETURN_DELIVERY",
		CONFIRM_COLLECT_MONEY: "CONFIRM_COLLECT_MONEY",
		CREATE_MONEY_RECEIPT: "CREATE_MONEY_RECEIPT",
		RETURN_SHIPMENT: "RETURN_SHIPMENT",
		ADD_CLIENT_ADDRESS: "ADD_CLIENT_ADDRESS",
		ADD_NEW_PRODUCT: "ADD_NEW_PRODUCT",
		ADD_NEW_SHIPMENT: "ADD_NEW_SHIPMENT",
		CONFIRMATION: "CONFIRMATION",
		MONEY_COLLECTION: "MONEY_COLLECTION",
		DEFAULT: "",
	},
	RIGHT_DRAWER_TYPES = {
		NOTIFICATION: "NOTIFICATION",
		CALENDAR_EVENTS: "CALENDAR_EVENTS",
	},
	CONFIRMATION_MODAL_CLOSE_TYPES = {
		LEAD_DELETE: "LEAD_DELETE",
	};
export { MODAL_BODY_TYPES, RIGHT_DRAWER_TYPES, CONFIRMATION_MODAL_CLOSE_TYPES };
